### ISSUE TITLE
Rename to `brainglobe-space`

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe-space#37]
The names of tools are inconsistent, and `bg` isn't very informative. We agreed in the [last dev meeting](https://github.com/brainglobe/BrainGlobe/discussions/350) to move to `brainglobe-xyz` as a standard. 

Moving the roadmap here so it shows in the issue:

- [x] Open a depreciation branch for the old name, `bg-space`. https://github.com/brainglobe/bg-space/pull/41
- [x] Open PR with metadata updates in prep for name change. https://github.com/brainglobe/bg-space/pull/42
  - [x] Bring package CI and deployment in line with other BG tools
- [x] Tag version 1.0.0
- [x] Push to PyPI
  - [x] 1st push will need to be explicit build and push
  - [x] Update the github secrets token to have permissions for the new package project on PyPI
- [x] Rename this repository
- [x] Stage dependency updates for [dependent packages](https://brainglobe.info/community/developers/repositories/brainglobe-meta/index.html#dependency-tree)
    - [x] `bg-atlasapi` (1.0.3) https://github.com/brainglobe/bg-atlasapi/pull/191
    - [x] `brainglobe-napari-io` (0.3.3) https://github.com/brainglobe/brainglobe-napari-io/pull/63
    - [ ] `morphapi` (0.2.2) https://github.com/brainglobe/morphapi/pull/52
    - [x] `brainrender` (2.1.5) https://github.com/brainglobe/brainrender/pull/320
    - [x] `brainreg` (1.0.4) https://github.com/brainglobe/brainreg/pull/176
    - [x] `brainglobe-meta` should now ship `brainglobe-space` rather than `bg-space`. We might as well pin the new versions of the above packages too. https://github.com/brainglobe/brainglobe-meta/pull/42
- [x] Stage any necessary website updates on [`brainglobe.github.io`]
(https://github.com/brainglobe/brainglobe.github.io) https://github.com/brainglobe/brainglobe.github.io/pull/143

**Comment by willGraham01** [comment]
Roadmap for this issue:

- [ ] Open a depreciation branch for the old name, `bg-space`.
  - [ ] Merge this branch and tag final version when ready
- [ ] Open PR with metadata updates in prep for name change
  - [ ] New release of `brainglobe-space` will be version 1.0.0
  - [ ] Stage alongside any necessary website updates on [`brainglobe.github.io`](https://github.com/brainglobe/brainglobe.github.io)
  - [ ] Stage dependency updates for [dependent packages](https://brainglobe.info/community/developers/repositories/brainglobe-meta/index.html#dependency-tree)
    - [ ] `bg-atlasapi`
    - [ ] `morphapi` (may not be necessary as not explicitly a dependence)
    - [ ] `brainrender` (may not be necessary as not explicitly a dependence)
    - [ ] `brainglobe-heatmap` (may not be necessary as not explicitly a dependence)
    - [ ] `brainreg`
    - [ ] `brainglobe-meta` should now ship `brainglobe-space` rather than `bg-space`. We might as well pin the new versions of the above packages too.
- [ ] Merge all necessary PRs for renamed package, tag version 1.0.0
- [ ] Push to PyPI
  - [ ] 1st push will need to be explicit build and push
  - [ ] Update the github secrets token to have permissions for the new package project on PyPI
- [ ] Rename this repository

**Comment by adamltyson** [comment]
BTW I think it's also used in `brainglobe-utils`, `brainglobe-workflows`, `brainglobe-napari-io` and `bg-atlasgen`.

Also, we should put it on conda-forge too

**Comment by willGraham01** [comment]
It's in `brainglobe-napari-io` but none of the others. `brainglobe-workflows` fetches the meta-package so should be OK with a new release

**Comment by willGraham01** [comment]
Am closing this since morphapi already has a bunch of outstanding issues that need fixing, and the PR branch should be easily rebase-able onto main.
