### ISSUE TITLE
[BUG] Possible typo in README?

### ISSUE THREAD

**Issue by niksirbi** [brainglobe/brainglobe-space#57]
In the README we find:

```python
source_space = bg.AnatomicalSpace(target_origin, stack.shape)
```
I would expect this to be:
```python
source_space = bg.AnatomicalSpace(source_origin, stack.shape)
```
If this is not a type, there should be some explanation for people that may be confused (like me).

**Comment by niksirbi** [comment]
Btw, the same applies to the corresponding page in `brainglobe.info`.

**Comment by vigji** [comment]
Looks like a bug indeed

**Comment by niksirbi** [comment]
I'll open the necessary PRs
